id: P004576
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:42:29.120941
source_metadata:
  id: bdr:W3CN7493
  title: གསེར་འོད་ས་བཅུ་མ།
  author: ''
  volumes:
    e535262c7add445db9879cba6535739c:
      image_group_id: I3CN7495
      title: ''
      volume_number: 1
      total_pages: 455
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
